src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Group_Chatter_Thread__c</fullName>
        <label>Group Chatter Thread</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Feed_Id__c</fullName>
        <inlineHelpText>Stores Id of Feed for SMS Cases</inlineHelpText>
        <label>SMS Feed Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/SMS_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Standard Settings for SMS Functionality (e.g. email to chatter and  sms chatter group)</description>
    <fields>
        <fullName>SMS_Group_id__c</fullName>
        <inlineHelpText>Group Id of Chatter Group used to notify agents of new message</inlineHelpText>
        <label>SMS Group Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Info_Group_Id__c</fullName>
        <inlineHelpText>New SMS with INFO as request get put in this group</inlineHelpText>
        <label>SMS Info Group Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_Update_Group_Id__c</fullName>
        <inlineHelpText>Group Id that updates to existing cases get posted in</inlineHelpText>
        <label>SMS Update Group Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SMS_User_Id__c</fullName>
        <inlineHelpText>Id of Chatter User that appears for auto-updates in Chatter Feed. Note - the context user for the email to chatter service MUST have update system fields for chatter permission</inlineHelpText>
        <label>SMS User Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>SMS Config</label>
</CustomObject>

src/objects/SMS_Message_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SMS Message Tracking</relationshipLabel>
        <relationshipName>SMS_Message_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FROM_Number__c</fullName>
        <label>FROM Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Matched_Case__c</fullName>
        <label>Matched Case</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Part__c</fullName>
        <defaultValue>99</defaultValue>
        <label>Message Part</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Message</label>
        <referenceTo>SMS_Message_Tracking__c</referenceTo>
        <relationshipLabel>SMS Message Tracking</relationshipLabel>
        <relationshipName>RelatedMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <inlineHelpText>Store Parse of Message to check for Auto Response requirements</inlineHelpText>
        <label>Request Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TO_Number__c</fullName>
        <label>TO Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>NEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATE TO PENDING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPDATE TO MULTI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SMS Message Tracking</label>
    <nameField>
        <displayFormat>SMS-{00000}</displayFormat>
        <label>SMS Message Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Message Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProcessSMStoCase.cls
public with sharing class ProcessSMStoCase {

    String sSubject; 
    String sautoresponse;
    String smessageThread;
    Case smscase;
    String sFinalMessage;
    String scode;
    Boolean bSuccess;
    List<String> AdditionalMessages;
    String sChatterMessage;
    List<SMS_Message_Tracking__c> smsmessageupdates;
    SMS_Message_Tracking__c msgtoprocess; 
    List<SMS_Message_Tracking__c> smsmessages;
    String sDate;
    Id GroupId; //Which Chatter Group Id to post notification in

public Boolean processsms(String emailSubject) {
    //Sandbox is added for Sandboxes
    sSubject = emailSubject.replace('Sandbox: ',''); 
    bSuccess = FALSE;
    AdditionalMessages = new List<String> ();
    smsmessageupdates = new List<SMS_Message_Tracking__c>();
    sDate = system.now().format();
    

    //Retrieve Inbound Message from Subject
    smsmessages = 
      [SELECT Id, Message__c, TO_Number__c, FROM_Number__c, Request_Type__c,
      Matched_Case__c, Type__c, Message_Part__c, Related_Message__c, 
      Related_Message__r.Case__c,
        (Select Id, Type__c, Message__c
          FROM RelatedMessages__r 
          ORDER By Message_Part__c ASC) 
      FROM SMS_Message_Tracking__c
      WHERE Id = :sSubject];

    if (smsmessages.size() > 0) {//record found
        msgtoprocess = smsmessages[0];
    
        String myPlainText= '';
        myPlainText = msgtoprocess.message__c;
       
       for (SMS_Message_Tracking__c s: msgtoprocess.RelatedMessages__r) {
                  if (s.Type__c == 'AUTO') {//auto response
                    sautoresponse = s.message__c;
                    s.Status__c = 'Processed';
                    smsmessageupdates.add(s);
                  }
                  else if (s.Type__c == 'UPDATE TO PENDING') {//auto response
                    s.Status__c = 'Process';
                    smsmessageupdates.add(s);
                  }
             }

             sFinalMessage = msgtoprocess.message__c;  

          if (msgtoprocess.type__c.equals('NEW') ) {
            //Should be a related message for Auto-Response
            
            smscase = SMSUtilities.createNewSMSCase(msgtoprocess);
            Contact caller = SMSUtilities.setupNewSMSCaller(msgtoprocess.FROM_Number__c);
            if (caller.Id == null) {
              insert caller;
            }

                Database.DMLOptions dmo = new Database.DMLOptions();
                dmo.assignmentRuleHeader.useDefaultRule= true;
                smscase.setOptions(dmo);
            smscase.ContactId = caller.Id;
            insert smscase;

              GroupId = SMS_Config__c.getValues('Default').SMS_Group_id__c;
                //Depending on the text of the SMS, we post into differnt groups for new messages
                //INFO goes into a separate group
                if (msgtoprocess.Request_Type__c == 'INFO') {
                  GroupId = SMS_Config__c.getValues('Default').SMS_Info_Group_Id__c;
                }

               
            scode = msgtoprocess.message__c.substringBefore(' ').toUpperCase(); 
            sChatterMessage = 'New SMS Thread started at ' + sDate + ' FROM New Caller'; 
                sChatterMessage += '\n';
                    if (sFinalMessage != null) {
                            sChatterMessage += ' Message: ' + sFinalMessage;
                    }     
       
            msgtoprocess.Status__c = 'Processed';
            smsmessageupdates.add(msgtoprocess);
            updateChatterforNewCases();
            updateSMSMessages(smscase.Id);
      
          } //end master if for NEW

          else if (msgtoprocess.type__c.equals('UPDATE TO PENDING') ) {
          //Find SMS Thread 
            smscase = [Select Id, CaseNumber, SMS_Feed_Id__c  from Case WHERE Id = :msgtoprocess.Related_Message__r.Case__c];

            String s = 'SMS Update received at ' + sDate + ' FROM Existing Caller'; 
                       s += '\n';
                       if (sFinalMessage != null) {
                       s += ' Message: ' + sFinalMessage;
                       }        
           
            FeedComment fc = new FeedComment (
            CreatedById = SMS_Config__c.getValues('Default').SMS_User_Id__c,
            CommentBody = s,
            CommentType = 'TextComment',
            FeedItemId = smscase.SMS_Feed_Id__c);
            insert fc;

            msgtoprocess.Status__c = 'Processed';
            smsmessageupdates.add(msgtoprocess);
            updateSMSMessages(msgtoprocess.Related_Message__r.Case__c);
            }


          else if (msgtoprocess.type__c.equals('UPDATE TO CASE') ) {
       //Find SMS Thread 
            smscase = [Select Id, CaseNumber, SMS_Feed_Id__c  from Case WHERE Id = :msgtoprocess.Matched_Case__c];

            String s = 'SMS Update received at ' + sDate + ' FROM Existing Caller'; 
                       s += '\n';
                       if (sFinalMessage != null) {
                       s += ' Message: ' + sFinalMessage;
                       }        
            
            FeedComment fc = new FeedComment (
            CreatedById = SMS_Config__c.getValues('Default').SMS_User_Id__c,
            CommentBody = s,
            CommentType = 'TextComment',
            FeedItemId = smscase.SMS_Feed_Id__c);
            insert fc;

            FeedItem groupfeeditem = new FeedItem (
            parentId = SMS_Config__c.getValues('Default').SMS_Update_Group_Id__c,
            CreatedById = SMS_Config__c.getValues('Default').SMS_User_Id__c,
            Body = s,
            Title = 'Update to SMS Case Number ' + smscase.caseNumber,// + sid[2],
            LinkURL = '/'+ msgtoprocess.Matched_Case__c,
            Type = 'LinkPost' );
            insert groupfeeditem;

            msgtoprocess.Status__c = 'Processed';
            smsmessageupdates.add(msgtoprocess);
            updateSMSMessages(smscase.Id);
            
      } //end master UPDATE if

  }//end the msg check if
      return bSuccess;
     
}

private void updateChatterforNewCases () {

 List<FeedItem> newfeeditems = new List<FeedItem>();
 
        FeedItem ufgroup = new FeedItem (
            CreatedById = SMS_Config__c.getValues('Default').SMS_User_Id__c,
            parentId = GroupId,
            Body = sFinalMessage,
            Title = 'New SMS Thread',
            LinkURL = '/'+ smscase.Id,
            Type = 'LinkPost' );
    newfeeditems.add(ufgroup);
    
        FeedItem ufcase = new FeedItem (
            CreatedById = SMS_Config__c.getValues('Default').SMS_User_Id__c,
            parentId = smscase.Id,
            Body = sChatterMessage,
            Title = 'New SMS Thread',
            Type = 'TextPost');
    newfeeditems.add(ufcase);
    
    
    List<FeedComment> fc = new List<FeedComment> ();
    fc.add(new FeedComment(
            CreatedById = SMS_Config__c.getValues('Default').SMS_User_Id__c,
            CommentBody = 'Auto Response Sent: ' + sautoresponse,
            CommentType = 'TextComment'));
   
  try {
        insert newfeeditems;
        for (FeedComment fu: fc) {
              fu.FeedItemId = newfeeditems[1].Id;
        }
        
        insert fc;

        //now store the chatter ids (Group and Feed)
        smscase.Group_Chatter_Thread__c = ufgroup.Id;
        smscase.SMS_Feed_Id__c = newfeeditems[1].Id;
        update smscase;
        bSuccess = TRUE;
        }


        catch (Exception Ex) {
          system.debug('### Email Failed' + Ex);    
          bSuccess =  FALSE;  
        }
     
} //end updateChatter

private void updateSMSMessages(Id CaseId) {
for (SMS_Message_Tracking__c s:  smsmessageupdates) {
            s.Matched_Case__c = CaseId;
            s.Case__c = CaseId;
            }
            
            update smsmessageupdates;
}



}