src/objects/SMS_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Standard Settings for SMS Functionality (e.g. email to chatter and  sms chatter group)</description>
    <fields>
        <fullName>Callback_URL__c</fullName>
        <label>Callback URL</label>
        <type>Url</type>
    </fields>
    <label>SMS Config</label>
</CustomObject>

src/objects/SMS_Message_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>SMS Message Tracking</relationshipLabel>
        <relationshipName>SMS_Message_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <label>Direction</label>
        <picklist>
            <picklistValues>
                <fullName>Inbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FROM_Number__c</fullName>
        <label>FROM Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TO_Number__c</fullName>
        <label>TO Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>SMS Message Tracking</label>
    <nameField>
        <displayFormat>SMS-{00000}</displayFormat>
        <label>SMS Message Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Message Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendSMSMessage.cls
public class SendSMSMessage {

public TwilioSms sms {get; private set;}
static TwilioAccount account = TwilioAPI.getDefaultAccount();

public SMS_Message_Tracking__c sendsms(sObject c, String smsmsg, String ToNumber, String fromNumber, Id FeedItemId) {

       Map<String, String> params = new Map<String, String>{
          'From' => fromNumber,
          'To' => ToNumber,
          'Body' => smsmsg,
          'StatusCallback' => SMS_Config__c.getValues('Default').Callback_URL__c
        };
        
        sms = account.getSmsMessages().create(params);
        
        SMS_Message_Tracking__c smstrack = new SMS_Message_Tracking__c();
        smstrack.SID__c = sms.getSid();
        smstrack.Status__c = 'Queued';
        smstrack.Direction__c = 'Outbound';
        smstrack.FROM_Number__c = fromNumber;
        smstrack.Message__c = smsmsg;
        smstrack.TO_Number__c = ToNumber;
        smstrack.Case__c = c.Id;
        insert smstrack; 
        
        if (FeedItemId != null) {
            String s = 'NEW SMS Sent at ' +  system.now().format() + ' FROM Agent'; 
                       s += '\n';
                       s += smsmsg;
                                           
            FeedComment fc = new FeedComment (
            CommentBody = s,
            CommentType = 'TextComment',
            FeedItemId = FeedItemId);
                       
            insert fc;
        }
        
    return smstrack; 
    }
    
    }